// Code generated by "mkwinsyscall_struct -struct doc"; DO NOT EDIT.

package printer

func (p *DOC_INFO_1) GetDocName() string {
	return utf16PtrToString(p.DocName)
}
func (p *DOC_INFO_1) GetOutputFile() string {
	return utf16PtrToString(p.OutputFile)
}
func (p *DOC_INFO_1) GetDatatype() string {
	return utf16PtrToString(p.Datatype)
}
func (p *DOC_INFO_1) GetDoc() Doc {
	return Doc{
		OutputFile: p.GetOutputFile(),
		Datatype:   p.GetDatatype(),
		DocName:    p.GetDocName(),
	}
}

type Doc struct {
	Datatype   string
	DocName    string
	OutputFile string
}
